name: EpicDrop
main: net.unknown.epicdrop.Core
version: '1.4.0b'
author: 'Unknown'
softdepend: [Vault]

commands:
    edrop:
      description: This is the basic on/off command.
      usage: /edrop
      permission: edrop.*
      permission-message: You don't have edrop.*
permissons:
   edrop.*:
       description: Gives access to all EpicDrop commands.
       children:
            edrop.config: true
            edrop.toggle: true
            edrop.drops: true
            edrop.reload: true
   edrop.config:
       description: Allows you to edit config In-Game through /edrop edit command.
       default: op
   edrop.toggle:
       description: Allows you to turn on/off EpicDrop.
       default: op
   edrop.drops:
       description: Allows you to turn on/off Drops.
       default: op
   edrop.reload:
       description: Allows you to reload the plugin.
       default: op