name: EpicDrop
main: net.unknown.epicdrop.Core
version: '1.1.1'
author: 'Unknown'
softdepend: [Vault]

commands:
    edrop:
      description: This is the basic on/off command.
      usage: /edrop
      permission: EpicServer.Admin.eDrop
      permission-message: You don't have EpicServer.Admin.eDrop
    bal:
      description: Used to check the balance of your money.
      usage: /bal
      permission: EpicDrop.Bal
      permission-message: You don't have EpicDrop.Bal
    balance:
      description: Used to check the balance of your money.
      usage: /balance
      permission: EpicDrop.Balance
      permission-message: You don't have EpicDrop.Balance
permissons:
   admin.*:
       description: Gives acces to all EpicDrop commands.
       children:
            admin.edrop: true
            admin.drops: true
            admin.reload: true
   admin.edrop:
       description: Allows you to turn on/off EpicDrop.
       default: op
   admin.drops:
       description: Allows you to turn on/off Drops.
       default: op
   admin.reload:
       description: Allows you to reload the plugin.
       default: op