name: EpicDrop
main: net.unknown.epicdrop.Core
version: '1.4.0b'
author: 'Unknown'
softdepend: [Vault]

commands:
    edrop:
      description: This is the basic on/off command.
      usage: /edrop
      permission: EpicServer.Admin.eDrop
      permission-message: You don't have EpicServer.Admin.eDrop
permissons:
   admin.*:
       description: Gives access to all EpicDrop commands.
       children:
            admin.edrop: true
            admin.drops: true
            admin.reload: true
            admin.config: true
   admin.config:
       description: Allows you to edit config In-Game through /edrop edit command.
       default: op
   admin.edrop:
       description: Allows you to turn on/off EpicDrop.
       default: op
   admin.drops:
       description: Allows you to turn on/off Drops.
       default: op
   admin.reload:
       description: Allows you to reload the plugin.
       default: op